[build]
  command = "pnpm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "24"
  PNPM_FLAGS = "--shamefully-hoist --frozen-lockfile"
  AUTH_TRUST_HOST = "true"

[dev]
  command = "pnpm dev"
  targetPort = 3000
  framework = "#custom"

[[plugins]]
  package = "@netlify/plugin-nextjs"
