'use client'

import { useMemo, useState } from 'react'
import { DndContext, DragEndEvent, useDraggable, useDroppable } from '@dnd-kit/core'
import { Check, Clock3, FileCheck2, Search, ShieldCheck, X } from 'lucide-react'
import { toast } from 'sonner'
import { kycDocuments } from '@/data/mock'
import { DocumentViewer, EmptyOperationalState } from '@/components/dashboard/operational'
import { StatusBadge } from '@/components/dashboard/components'
import type { KycDocument, KycStatus } from '@/types/index'

const labels: Record<KycStatus, string> = { PENDING: 'Pending Review', VERIFIED: 'Verified', REJECTED: 'Rejected', EXPIRED: 'Rejected' }
const docLabel = (value: KycDocument['type']) => value === 'DRIVERS_LICENSE' ? "Driver's License" : value.replaceAll('_', ' ')
const queueHours = (index: number) => index % 5 === 0 ? 28 : 3 + index

function KycCard({ doc, index, onOpen }: { doc: KycDocument; index: number; onOpen: () => void }) {
  const { attributes, listeners, setNodeRef, transform, isDragging } = useDraggable({ id: doc.id })
  const initials = doc.applicantName.split(' ').map((part) => part[0]).slice(0, 2).join('')
  const hours = queueHours(index)
  return <button ref={setNodeRef} {...listeners} {...attributes} onClick={onOpen} style={transform ? { transform: `translate3d(${transform.x}px, ${transform.y}px, 0)`, zIndex: 10 } : undefined} className={`kyc-card w-full text-left transition hover:scale-[1.02] hover:shadow-xl ${isDragging ? 'opacity-50' : ''}`}>
    <div className="flex items-center justify-between"><div className="avatar bg-gradient-to-br from-amber-600 to-amber-800">{initials}</div><StatusBadge status={doc.status} /></div>
    <p className="mt-4 font-medium text-slate-100">{doc.applicantName}</p><p className="mt-1 text-xs text-slate-400">+234 803 555 0192</p>
    <div className="mt-3 flex items-center justify-between gap-2 text-xs text-slate-500"><span className="truncate">{docLabel(doc.type)}</span><span className={hours > 24 ? 'text-amber-400' : ''}><Clock3 className="mr-1 inline size-3" />{hours}h ago</span></div>
    {hours > 24 && doc.status === 'PENDING' && <p className="mt-3 text-[11px] font-medium text-amber-400">● Urgent review</p>}
  </button>
}

function Column({ status, docs, onOpen }: { status: KycStatus; docs: KycDocument[]; onOpen: (doc: KycDocument) => void }) {
  const { setNodeRef, isOver } = useDroppable({ id: status })
  return <section ref={setNodeRef} className={`panel border-t-2 p-4 ${status === 'PENDING' ? 'border-t-amber-500' : status === 'VERIFIED' ? 'border-t-emerald-500' : 'border-t-rose-500'} ${isOver ? 'bg-slate-800/70' : ''}`}>
    <div className="mb-4 flex items-center justify-between"><div><h3 className="font-semibold">{labels[status]}</h3><p className="mt-1 text-xs text-slate-500">{docs.length} documents</p></div><span className="rounded-full bg-slate-800 px-2 py-1 text-xs text-slate-300">{docs.length}</span></div>
    <div className="flex min-h-96 flex-col gap-3">{docs.length ? docs.map((doc, index) => <KycCard key={doc.id} doc={doc} index={index} onOpen={() => onOpen(doc)} />) : <EmptyOperationalState title="No documents in this stage" description="Documents will appear here as verification progresses." />}</div>
  </section>
}

function DetailModal({ doc, onClose, onDecision }: { doc: KycDocument; onClose: () => void; onDecision: (status: KycStatus) => void }) {
  const [checked, setChecked] = useState([false, false, false, false])
  const [rejecting, setRejecting] = useState(false)
  const allChecked = checked.every(Boolean)
  const toggle = (index: number) => setChecked((current) => current.map((value, i) => i === index ? !value : value))
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/80 p-0 backdrop-blur-sm sm:p-6"><div className="flex h-full w-full max-w-6xl flex-col overflow-hidden border border-slate-700 bg-slate-900 shadow-2xl sm:h-[90vh] sm:rounded-xl"><div className="flex items-center justify-between border-b border-slate-800 px-5 py-4"><div><p className="eyebrow">Document review</p><h3 className="font-semibold text-slate-100">{doc.applicantName} · {docLabel(doc.type)}</h3></div><button className="icon-button" aria-label="Close document review" onClick={onClose}><X /></button></div><div className="grid min-h-0 flex-1 gap-0 overflow-y-auto lg:grid-cols-[1.1fr_.9fr]"><div className="p-4 sm:p-6"><DocumentViewer name={`${doc.id}-${docLabel(doc.type)}.jpg`} /></div><div className="flex flex-col border-l border-slate-800"><div className="flex-1 space-y-5 p-5"><div className="panel p-4"><p className="text-xs uppercase tracking-widest text-slate-500">Applicant</p><p className="mt-2 font-semibold">{doc.applicantName}</p><p className="mt-1 text-sm text-slate-400">+234 803 555 0192</p><p className="mt-3 text-sm text-slate-300">Loan amount <strong className="float-right">₦750,000</strong></p></div><div><div className="mb-3 flex items-center gap-2"><FileCheck2 className="size-4 text-amber-400" /><h4 className="font-semibold">OCR Extracted Data</h4></div><div className="grid gap-3 sm:grid-cols-2">{Object.entries(doc.ocrData ?? {}).slice(0, 5).map(([key, value]) => <label key={key} className="field-label"><span>{key}</span><input defaultValue={value} className="form-control" /></label>)}</div></div><div><h4 className="mb-3 font-semibold">Verification Checklist</h4><div className="flex flex-col gap-2">{['ID Document Valid', 'Photo Matches Applicant', 'Address Confirmed', 'Not Expired'].map((item, index) => <label key={item} className="flex items-center gap-3 rounded-lg border border-slate-800 p-3 text-sm text-slate-300"><input type="checkbox" checked={checked[index]} onChange={() => toggle(index)} className="size-4 accent-amber-500" />{item}</label>)}</div></div>{rejecting && <textarea className="form-control min-h-24 w-full resize-none" placeholder="Reason for rejection" aria-label="Rejection reason" />}</div><div className="sticky bottom-0 flex flex-wrap gap-2 border-t border-slate-800 bg-slate-900 p-4"><button className="primary-button bg-emerald-500 hover:bg-emerald-400 disabled:cursor-not-allowed disabled:opacity-50" disabled={!allChecked} onClick={() => onDecision('VERIFIED')}><Check /> Verify & Approve</button><button className="danger-button" onClick={() => rejecting ? onDecision('REJECTED') : setRejecting(true)}>{rejecting ? 'Confirm Reject' : 'Reject'}</button><button className="secondary-button border-amber-500/40 text-amber-300" onClick={() => { toast.success('More information requested'); onClose() }}>Request More Info</button></div></div></div></div></div>
}

export default function KycPage() { const [docs, setDocs] = useState(kycDocuments); const [active, setActive] = useState<KycDocument>(); const [search, setSearch] = useState(''); const [type, setType] = useState('ALL'); const [tab, setTab] = useState<'ALL' | KycStatus>('ALL'); const filtered = useMemo(() => docs.filter((doc) => doc.applicantName.toLowerCase().includes(search.toLowerCase()) && (type === 'ALL' || doc.type === type) && (tab === 'ALL' || doc.status === tab)), [docs, search, type, tab]); const move = (event: DragEndEvent) => { if (!event.over) return; const status = event.over.id as KycStatus; setDocs((current) => current.map((doc) => doc.id === event.active.id ? { ...doc, status } : doc)); toast.success(`Document moved to ${labels[status]}`) }; return <DndContext onDragEnd={move}><div className="page-stack"><div className="page-intro"><div><p className="eyebrow">Compliance operations</p><h2 className="page-heading">KYC Verification Center</h2><p className="page-lede">Review identity documents and keep approvals moving.</p></div><div className="flex flex-wrap gap-2"><div className="pill-stat"><ShieldCheck /> {docs.filter((doc) => doc.status === 'PENDING').length} pending review</div><div className="pill-stat border-emerald-500/30 text-emerald-300"><Check /> {docs.filter((doc) => doc.status === 'VERIFIED').length} verified today</div><div className="pill-stat border-rose-500/30 text-rose-300"><X /> {docs.filter((doc) => doc.status === 'REJECTED').length} rejected today</div></div></div><div className="panel flex flex-wrap items-center gap-3 p-3"><div className="input-wrap min-w-56 flex-1"><Search /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search applicant or phone" aria-label="Search applicant" /></div><select value={type} onChange={(event) => setType(event.target.value)} className="select-control" aria-label="Document type"><option value="ALL">All document types</option><option value="NIN">NIN</option><option value="DRIVERS_LICENSE">Driver&apos;s License</option><option value="PASSPORT">Passport</option></select><div className="segmented">{[['ALL', 'All'], ['PENDING', 'Pending'], ['VERIFIED', 'Verified'], ['REJECTED', 'Rejected']].map(([value, label]) => <button key={value} className={tab === value ? 'selected' : ''} onClick={() => setTab(value as typeof tab)}>{label}</button>)}</div></div><div className="grid gap-4 xl:grid-cols-3">{(['PENDING', 'VERIFIED', 'REJECTED'] as KycStatus[]).map((status) => <Column key={status} status={status} docs={filtered.filter((doc) => doc.status === status)} onOpen={setActive} />)}</div></div>{active && <DetailModal doc={active} onClose={() => setActive(undefined)} onDecision={(status) => { setDocs((current) => current.map((doc) => doc.id === active.id ? { ...doc, status } : doc)); toast.success(status === 'VERIFIED' ? 'KYC approved' : 'KYC rejected'); setActive(undefined) }} />}</DndContext> }
