'use client'
import { useEffect, useRef, useState } from 'react'
import { Check, CheckCircle2, Download, FileText, Image as ImageIcon, Paperclip, RotateCw, Send, ZoomIn, ZoomOut } from 'lucide-react'
import { toast } from 'sonner'

export function DocumentViewer({name='identity-document.jpg'}:{name?:string}) { const [zoom,setZoom]=useState(1); const [rotation,setRotation]=useState(0); return <div className="flex min-h-[360px] flex-col overflow-hidden rounded-xl border border-slate-700 bg-slate-950"><div className="flex items-center justify-between border-b border-slate-800 px-3 py-2"><span className="flex items-center gap-2 text-xs text-slate-400"><FileText className="size-4 text-amber-400"/>{name}</span><div className="flex items-center gap-1"><button className="icon-button" aria-label="Zoom out" onClick={()=>setZoom(Math.max(1,zoom-.5))}><ZoomOut/></button><span className="w-10 text-center font-mono text-xs text-slate-400">{zoom}x</span><button className="icon-button" aria-label="Zoom in" onClick={()=>setZoom(Math.min(2,zoom+.5))}><ZoomIn/></button><button className="icon-button" aria-label="Rotate document" onClick={()=>setRotation((rotation+90)%360)}><RotateCw/></button><button className="icon-button" aria-label="Download document" onClick={()=>toast.success('Document download queued')}><Download/></button></div></div><div className="document-preview flex-1 overflow-hidden"><div className="flex min-h-64 w-4/5 flex-col items-center justify-center rounded-lg border border-slate-700 bg-slate-900 transition-transform" style={{transform:`scale(${zoom}) rotate(${rotation}deg)`}}><ImageIcon className="size-16 text-amber-500/60"/><p className="mt-3 text-sm text-slate-400">Secure document preview</p><p className="mt-1 font-mono text-xs text-slate-600">OCR ready · encrypted at rest</p></div></div></div> }
export function ChatBubble({outbound,body,time,status}:{outbound:boolean;body:string;time:string;status?:'sent'|'failed'}) { return <div className={`flex ${outbound?'justify-end':''}`}><div className={`max-w-[76%] rounded-2xl p-3 text-sm ${outbound?'rounded-tr-sm bg-amber-900/30 text-amber-50':'rounded-tl-sm bg-slate-800 text-slate-200'} ${status==='failed'?'border border-rose-500/50':''}`}><p>{body}</p><div className="mt-2 flex items-center justify-end gap-2 text-[10px] text-slate-500">{status==='failed'&&<button className="text-rose-300" onClick={()=>toast.info('Retry queued')}>Retry</button>}{time}{outbound&&status!=='failed'&&<Check className="size-3"/>}</div></div></div> }
export function MessageInput({onSend}:{onSend:(value:string)=>void}) { const [value,setValue]=useState(''); const ref=useRef<HTMLTextAreaElement>(null); useEffect(()=>{if(ref.current){ref.current.style.height='auto';ref.current.style.height=Math.min(ref.current.scrollHeight,140)+'px'}},[value]); const submit=()=>{if(!value.trim())return;onSend(value.trim());setValue('')}; return <div className="flex items-end gap-2 border-t border-slate-800 p-3"><button className="icon-button" aria-label="Attach file" onClick={()=>toast.info('Attachment picker opened')}><Paperclip/></button><textarea ref={ref} value={value} onChange={e=>setValue(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing&&e.keyCode!==229){e.preventDefault();submit()}}} rows={1} placeholder="Write a reply..." className="form-control min-h-11 max-h-36 flex-1 resize-none"/><button className="primary-button min-h-11 min-w-11 px-3" disabled={!value.trim()} aria-label="Send message" onClick={submit}><Send/></button></div> }
export function EmptyOperationalState({title,description}:{title:string;description:string}) { return <div className="flex min-h-48 flex-col items-center justify-center gap-3 text-center"><CheckCircle2 className="size-10 text-slate-600"/><h3 className="font-semibold text-slate-300">{title}</h3><p className="max-w-sm text-sm text-slate-500">{description}</p></div> }
